algoritmo "exercicio7"
// Função : Converter temperatura de Celsius para Fahrenheit
// Autor :
// Data : 29/09/2025
// Seção de Declarações
var
c, f: real

inicio
// Pede ao usuário a temperatura em graus Celsius
escreva("Digite a temperatura em graus Celsius: ")
leia(C)

// Converte Celsius para Fahrenheit usando a fórmula
f <- (9*c+160)/5

// Exibe o resultado da conversão
escreval(" ")
escreva("Temperatura em Fahrenheit: ", F)
escreval(" ")


fimalgoritmo
