algoritmo "Exercicio1"
// Função : Esse exercício pede dois números e mostra a soma deles na tela.
// Função :
// Autor :
// Data : 24/09/2025
// Seção de Declarações
var
n1, n2: inteiro

inicio

// Pede para o usuário digitar o primeiro e o segundo número, lê e guarda em n1 e n2
escreva("Digite o primeiro número: ")
leia(n1)
escreva("Digite o segundo número: ")
leia(n2)

// Calcula e mostra o resultado da soma
escreva("A soma dos números é: ",n1+n2)

fimalgoritmo
